<script setup lang="ts">
import { computed } from 'vue'
import type { VenueDetail } from '../../model/venue'
import VenueMap from '@/features/map/components/VenueMap.vue'
import VenueMarker from '@/features/map/components/VenueMarker.vue'
import { getVenueImage } from '../../utils'
import AppLucideIcon from '@/components/ui/AppLucideIcon.vue'
import DetailSection from './DetailSection.vue'
const props = defineProps<{ venue: VenueDetail }>()
const imageUrl = computed(() => getVenueImage(props.venue))
</script>
<template><DetailSection v-if="venue.address || venue.location" title="Joylashuv"><p v-if="venue.address" class="location__address"><AppLucideIcon name="map-pin" /><strong>{{ venue.address.formatted }}</strong></p><div v-if="venue.location" class="location"><VenueMap :center="venue.location" :zoom="15"><VenueMarker :venue="venue" selected /></VenueMap><div v-if="imageUrl" class="location__photo"><img :src="imageUrl" :alt="venue.name" width="56" height="56" loading="lazy" decoding="async"/><span>{{ venue.name }}</span></div><a :href="`https://www.openstreetmap.org/?mlat=${venue.location.latitude}&mlon=${venue.location.longitude}`" target="_blank" rel="noopener noreferrer"><AppLucideIcon name="external-link" :size="17" />Xaritada ochish</a></div></DetailSection></template>
<style scoped>.location__address{margin:0;display:flex;gap:var(--space-2);font-size:var(--font-size-md)}.location { position:relative;height:230px;overflow:hidden;border: 1px solid var(--color-border); border-radius: var(--radius-lg);background:var(--color-surface-muted) }.location :deep(.venue-map),.location :deep(.venue-map__canvas){min-height:230px;height:230px}.location__photo{position:absolute;z-index:500;right:var(--space-3);bottom:var(--space-3);left:var(--space-3);display:flex;align-items:center;gap:var(--space-2);padding:var(--space-2);padding-right:150px;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:color-mix(in srgb,var(--color-surface) 96%,transparent);box-shadow:var(--elevation-2);backdrop-filter:blur(8px)}.location__photo img{width:56px;height:56px;flex:0 0 auto;border-radius:var(--radius-md);object-fit:cover}.location__photo span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:var(--font-size-sm);font-weight:var(--font-weight-semibold)}.location a { position:absolute;z-index:501;right:calc(var(--space-3) + var(--space-2));bottom:calc(var(--space-3) + var(--space-2) + 6px);min-height: var(--touch-target-min); display: inline-flex; align-items: center;padding-inline:var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-md);color: var(--color-text-primary);background:var(--color-surface);box-shadow:var(--elevation-1);text-decoration:none;font-size:var(--font-size-sm);font-weight:var(--font-weight-semibold); }@media(max-width:360px){.location__photo{padding-right:var(--space-2);bottom:70px}.location a{right:var(--space-3);bottom:var(--space-3)}}</style>
